server:
  port: 8080
spring:
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: master
      username: geek-user
      password: geek-pass